config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
	root 'welcome#home'
	get 'about', to: 'welcome#about'
	resources :accounts

	get 'signup', to: 'users#new'
	resources :users, except: [:new] 

	get 'login', to: 'sessions#new'
	post 'login', to: 'sessions#create'
	delete 'logout', to: 'sessions#destroy' 

end

app/models/account.rb
class Account < ApplicationRecord
	belongs_to :user
	validates :name, presence: true, length: { minimum: 2, maximum: 20 }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	has_many :accounts 
	before_save { self.email = email.downcase }
	validates :username, presence: true,
		uniqueness: { case_sensitive: false },
		length: { minimum: 3, maximum: 25 }

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

	validates :email, presence: true, length: { maximum: 105 },
		uniqueness: { case_sensitive: false },
		format: { with: VALID_EMAIL_REGEX } 
	has_secure_password 

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

	before_action :set_account, only: [:edit, :update, :show, :destroy]
	before_action :require_user, except: [:index, :show]
	before_action :require_same_user, only: [:edit, :update, :destroy] 

	def new
		@account = Account.new
	end

	def create
		@account = Account.new(account_params)
		@account.user = User.first 
		if @account.save
			flash[:success] = "account created!"
			redirect_to account_path(@account)
		else
			render :new
		end		
	end

	def show
		@accounts = Account.find(params[:id]) 
	end

	def edit	
	end

	def update		
		if @account.update(account_params)
			flash[:success] = "account updated!"
			redirect_to account_path(@account)
		else
			render :edit
		end		
	end

	def index
		# @accounts = Account.all
		@accounts = Account.paginate(page: params[:page], per_page: 5)  
	end

	def destroy
		@account.destroy
		flash[:danger] = "account #{@account.name} successfully deleted!"
		redirect_to accounts_path
	end

	private
	
	def set_account
		@account = Account.find(params[:id])	
	end
	
	def account_params
		params.require(:account).permit(:name, :motto)	
	end
	
	def require_same_user
		if current_user != @account.user
			flash[:danger] = "You can only edit or delete your own articles"
			redirect_to root_path
		end

	end 
		
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	protect_from_forgery with: :exception

	helper_method :current_user, :logged_in?

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def logged_in?
		!!current_user
	end

	def require_user
		if !logged_in?
			flash[:danger] = "You must be logged in to perform that action"
			redirect_to root_path
		end
	end

end 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new

	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			session[:user_id] = user.id
			flash[:success] = "Welcome to iChanknows #{user.username}"
			redirect_to user_path(user)
		else
			flash.now[:danger] = "email or password is incorrect"
			render 'new' 
		end
	end

	def destroy
		session[:user_id] = nil
		flash[:success] = "You have logged out"
		redirect_to root_path 
	end

end 

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	before_action :set_user, only: [:edit, :update, :show]
	before_action :require_same_user, only: [:edit, :update] 
	
	def new
		@user = User.new
	end
	def create
		@user = User.new(user_params)
		if @user.save
			session[:user_id] = @user.id
			flash[:success] = "Welcome to the iChanKnows #{@user.username}"
			redirect_to user_path(@user)
		else
			render 'new'
		end
	end

	def show
		@user_accounts = @user.accounts.paginate(page: params[:page], per_page: 2) 
	end 

	def edit
	end

	def index
		@users = User.paginate(page: params[:page], per_page: 2) 
	end 

	def update
		if @user.update(user_params)
			flash[:success] = "Your account was updated successfully"
			redirect_to accounts_path
		else
			render 'edit'
		end
	end 
	
	private
	def user_params
		params.require(:user).permit(:username, :email, :password)
	end

	def set_user
		@user = User.find(params[:id])
	end

	def require_same_user
		if current_user != @user
			flash[:danger] = "You can only edit your own account"
			redirect_to root_path
		end
	end
end 

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	
	def home
		redirect_to accounts_path if logged_in? 
	end

	def about
		
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	def gravatar_for(user, options = { size: 80})
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.username, class: "img-circle")
	end 

end

app/views/accounts/_accounts.html.erb
<% obj.each do |account| %>
<div class="row">
	<div class="col-xs-8 col-xs-offset-2">
		<div class="well well-lg">
			<div class="account-name">
				<%= link_to account.name, account_path(account) %>
			</div>
			<div class="account-body">
				<%= truncate(account.motto, length: 100) %>
				<div class="account-meta-details">
					<small>Created by: <%= account.user.username if account.user%>,
					<%= time_ago_in_words(account.created_at) %> ago,
					last updated: <%= time_ago_in_words(account.updated_at) %> ago</small>
				</div> 
			</div>
			<% if logged_in? && current_user == account.user %> 
			<div class="account-actions">
				<%= link_to "Edit this account", edit_account_path(account), class: "btn btn-xs btn-primary" %>
				<%= link_to "Delete this account", account_path(account), method: :delete,
				data: { confirm: "Are you sure you want to delete the account?"},
				class: "btn btn-xs btn-danger" %>
			</div>
			<% end %>
		</div>
	</div>
</div>
<% end %> 

app/views/accounts/_form.html.erb
<%= form_for(@account, :html => {class: "form-horizontal", role: "form"}) do |f| %>
	<div class="form-group">
		<div class="control-label col-sm-2">
			<%= f.label :name %> 
		</div>
		<div class="col-sm-8">
			<%= f.text_field :name, class: "form-control", placeholder: "account name", autofocus: true %> 
		</div>
				
	</div>

	<div class="form-group">
		<div class="control-label col-sm-2">
			<%= f.label :motto %>
		</div>
		<div class="col-sm-8">
			<%= f.text_area :motto, rows: 10, class: "form-control", placeholder: "your motto" %> 
		</div>			
	</div>
	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<%= f.submit class: 'btn btn-primary btn-lg' %>
		</div>	
	</div>
<% end %>

<div class="col-xs-4 col-xs-offset-4">
	[ <%= link_to 'Cancel request and return to accounts list', accounts_path %> ]
</div>
<%= render 'shared/errors', obj: @account %>

app/views/accounts/edit.html.erb
<h1 align="center">edit account</h1>
<%= render 'form' %>

app/views/accounts/index.html.erb
<h1 align="center">Listing of all accounts </h1>
<div align="center">
	<%= will_paginate  %>
</div>
<%= render 'accounts', obj: @accounts %>
<div align="center">
	<%= will_paginate  %>
</div>

app/views/accounts/new.html.erb
<h1 align="center">new account</h1>
<%= render 'form' %>

app/views/accounts/show.html.erb
<h2 align="center"><%= @account.name %></h2>
<div class="well col-xs-8 col-xs-offset-2">


<% if @account.user %>
	<ul class="listing">
		<div class="row center">
			<div class="col-md-4 col-md-offset-4">
				<li>Created by:</li>
				<li>
					<%= link_to gravatar_for(@account.user), user_path(@account.user) %>
						
				</li>
				<li class="account-title">
					<%= link_to @account.user.username, user_path(@account.user) %>
				</li>
				<li>
					<small>
						<%= pluralize(@account.user.accounts.count, "accounts") if @account.user.accounts %>
					</small>
				</li>
			</div>
		</div>
	</ul>
<% end %>

<% if logged_in? && current_user == @account.user %> 
	<h4 class="center description"><strong>Motto:</strong></h4>
	<hr>
	<%= simple_format(@account.motto) %>
	<div class="account-actions">
		<%= link_to "Edit this account", edit_account_path(@account), class: "btn btn-xs btn-primary" %>
		<%= link_to "Delete this account", account_path(@account), method: :delete,
		data: { confirm: "Are you sure you want to delete this account?"},
		class: "btn btn-xs btn-danger" %>
<% end %> 
		<%= link_to "View all accounts", accounts_path, class: "btn btn-xs btn-success" %>
	</div>
</div> 

app/views/layouts/_footer.html.erb
<div class="container">
	<footer class="footer">
		<small>
		Copyright © <a href="enter in a link here">A Web Development Project</a>
		by <a href="enter in a link here">Christian Eugenio</a>
		</small>
		<nav>
			<ul>
				<li><%= link_to "About", about_path %></li>
			</ul>
		</nav>
	</footer>
</div> 

app/views/layouts/_messages.html.erb
<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
		<% flash.each do |name, msg| %>
		<div class='alert alert-<%="#{name}" %>'>
			<a href="#" class="close" data-dismiss="alert">×</a>
			<%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
		</div>
		<% end %>
	</div>
</div>    

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    <%= link_to 'iChanKnows', root_path, class:"navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <li><%= link_to "Accounts", accounts_path %></li>
      <li><%= link_to "Users", users_path %></li>
      <% if logged_in? %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "New Account", new_account_path %></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      <% end %>
      </ul>
      <form class="navbar-form navbar-left" role="search" >
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li><%= link_to 'Log out', logout_path, method: :delete %></li>
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Your Profile<span class="caret"></span></a>
          <ul class="dropdown-menu">
          <li><%= link_to "Edit your profile", edit_user_path(current_user) %></li>
          <li><%= link_to "View your profile", user_path(current_user) %></li>
          <li><a href="#">Something else here</a></li>
          <li role="separator" class="divider"></li>
          <li><a href="#">Separated link</a></li>
          </ul>
          </li>
        <% else %>
          <li><%= link_to 'Log in', login_path %></li>
          <li><%= link_to 'Sign up', signup_path %></li>
        <% end %>        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PracticeProj</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <div class="container">
      <%= yield %>
    </div> 
    <%= render 'layouts/footer' %> 
    <%= debug(params) if Rails.env.development? %> 
  </body>
</html>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="row">
	<div class="col-xs-8 col-xs-offset-2">
		<div class="panel panel-danger">
			<div class="panel-heading">
				<h2 class="panel-title">you got
					<%= pluralize(obj.errors.count, "error") %> while saving
				</h2>
				<div  class="panel-body">
					<ul>
					<% obj.errors.full_messages.each do |msg| %>
						<li>
							<%= msg %>
						</li>
					<% end %>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>
	<div class="form-group">
		<div class="control-label col-sm-2">
			<%= f.label :username %> 
		</div>
		<div class="col-sm-8">
			<%= f.text_field :username, class: "form-control", placeholder: "enter username", autofocus: true %> 
		</div>
				
	</div>

	<div class="form-group">
		<div class="control-label col-sm-2">
			<%= f.label :email %>
		</div>
		<div class="col-sm-8">
			<%= f.email_field :email, class: "form-control", placeholder: "enter your email" %> 
		</div>			
	</div>

	<div class="form-group">
		<div class="control-label col-sm-2">
			<%= f.label :password %>
		</div>
		<div class="col-sm-8">
			<%= f.password_field :password, class: "form-control", placeholder: "enter password" %> 
		</div>			
	</div>

	<div class="form-group">
		<div class="col-sm-offset-2 col-sm-10">
			<%= f.submit(@user.new_record? ? "Sign up" : "Update account" ,class: 'btn btn-primary btn-lg') %>
		</div>	
	</div>
<% end %>

<div class="col-xs-4 col-xs-offset-4">
	[ <%= link_to 'Cancel request and return to accounts list', accounts_path %> ]
</div>
<%= render 'shared/errors', obj: @user %>

app/views/users/edit.html.erb
<h1 align="center">Edit this account</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 align="center">All Alpha Bloggers</h1>
<div align="center">
	<%= will_paginate %>
	<% @users.each do |user| %>
		<ul class="listing">
			<div class="row">
				<div class="well col-md-4 col-md-offset-4">
				<li>
					<%= link_to gravatar_for(user), user_path(user) %>
				</li>
				<li class="account-title">
					<%= link_to user.username, user_path(user) %>
				</li>
				<li>
					<small><%= pluralize(user.accounts.count, "account") if user.accounts %></small>
				</li>
				</div>
			</div>
		</ul>
	<% end %>
	<%= will_paginate %>
</div> 

app/views/users/new.html.erb
<h1 align="center">Sign up for iChanknows</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username %>'s page</h1>

<div class="row">
	<div class="col-md-4 col-md-offset-4 center">
	<%= gravatar_for @user, size: 150 %>
	</div>
</div>

<h4 align="center"><%= @user.username %>'s accounts</h4>

<div class="center">
	<%= will_paginate @user_accounts %>
</div> 
<%= render 'accounts/accounts', obj: @user.accounts %>

<div class="center">
	<%= will_paginate @user_accounts %>
</div> 

app/views/welcome/about.html.erb
<h1>aboutpage</h1>

<%= link_to 'home page', root_path %>

app/views/welcome/home.html.erb
<div class="center jumbotron">
	<h1>Welcome to iChanknows</h1>
	<%= link_to 'Sign up now', signup_path,class: "btn btn-primary btn-xlarge"  %>  
</div>